name: Publish Release
run-name: Publish Release ${{ github.ref_name }}

concurrency:
  group: release

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish to Maven Central
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_sonatype.username: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype.password: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_gpg.key: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_gpg.password: ${{ secrets.GPG_PASSWORD }}
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
